

module.exports = {
  PLAID_PUBLISHABLE_KEY:process.env.PLAID_PUBLISHABLE_KEY,
  PLAID_CLIENT_ID:process.env.PLAID_CLIENT_ID,
  PLAID_SECRET:process.env.PLAID_SECRET, 
  STRIPE_SECRET_KEY:process.env.STRIPE_SECRET_KEY,
  PLAID_SECRET_SAND:process.env.PLAID_SECRET_SAND,
  STRIPE_SECRET_KEY_SAND:process.env.STRIPE_SECRET_KEY_SAND,
  STRIPE_PUBLIC_KEY_SAND:process.env.STRIPE_PUBLIC_KEY_SAND,
};
